### ISSUE TITLE
Graphic bug: see through blocks adjacent to Oyster Basket

### ISSUE THREAD

**Issue by jolandepoel** [kylertlove/Oysters#17]
I'm playing All Of Fabric 2 via the Twitch launcher and when I place an oyster basket on sand, the sand below it gets see through. Like, disappears (see picture). This also happens to sand on the sides of the oyster basket, if there happen to be any. 

My graphic settings are all on fast, no vsync, no shadows, all particles, mipmap levels: 0, if that helps any in determining the cause. 

![image](https://user-images.githubusercontent.com/17624489/75462254-423bec80-5984-11ea-9bfd-f3a766e94577.png)

**Comment by MayliSong** [comment]
I have the same problem and completely different graphical settings, so I guess it isn't your settings?

**Comment by kylertlove** [comment]
Will look into it.  This is for 1.15.2 correct?

**Comment by kylertlove** [comment]
The 1.15.2 update had changed some of the rendering hooks.  Just tested and pushed v0.1.5 up to curseforge with the fix.  should be good once the modpack updates
